// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Link struct {
	ID      string `bson:"_id"     json:"id"`
	Title   string `bson:"title"   json:"title"`
	Address string `bson:"address" json:"address"`
	User    *User  `bson:"user"    json:"user"`
}

type Login struct {
	Name     string `bson:"name"     json:"name"`
	Password string `bson:"password" json:"password"`
}

type NewLink struct {
	Title   string `bson:"title"   json:"title"`
	Address string `bson:"address" json:"address"`
}

type NewUser struct {
	Name     string `bson:"name"     json:"name"`
	Password string `bson:"password" json:"password"`
}

type RefreshToken struct {
	Token string `json:"token"`
}

type User struct {
	ID   string `bson:"id"   json:"id"`
	Name string `bson:"name" json:"name"`
}
